Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print（"昨天乌龟丢了，我很伤心，就好像我和ssh分开了一样")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"我们分开过很多次，但似乎每次都没有成功")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"就像我们每次都没有很好一样——不好不坏，苟延残喘")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"ssh有不回我的信息过，有拉黑过我，有删除过我，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"有在大马路上转身就走迈着自信的步伐，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"有三分钟之内删了我们的情侣空间，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"有在weibo上发过似是而非的话并且叫它作智者见智，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"有吼过我，有打过我，有威胁过我，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"最后，也有丢过我们的乌龟")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"——所有作为一个坏人应该做的事，他都做得一件不剩")
SyntaxError: invalid character '（' (U+FF08)
>>>  print（"可是呢，我们居然还是在一起，苟延残喘，这可真是个迷")
 
SyntaxError: unexpected indent
>>> print（"10月初，我们在github上互关")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"ssh一开始写过一些东西")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"那些东西不仅像流水账，而且有时候和事实不符")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"它们在一定程度上扭曲了事实真正的样子，就像ssh的意识")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"水扭曲了水杯里的筷子，三棱镜改变了光传播的方向，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"ssh的意识编造了一个只存在于他脑海里的真相")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"我希望有一天，西湖，是西湖，么？")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"或许是钱塘江，可以回来，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"让我再看到他矫健的步伐")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"就像我们奄奄一息的感情，")
SyntaxError: invalid character '（' (U+FF08)
>>> print（"有一天又有了新的开始")
SyntaxError: invalid character '（' (U+FF08)
>>> 